services:
  app:
    build: .
    ports:
      - "8501:8501"
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./auth/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - app
    restart: unless-stopped