services:
  app:
    build: .
    environment:
      - DEBUG=False
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-temporary-key-change-in-production}
      - DJANGO_SETTINGS_MODULE=returns_viz.settings
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-http://localhost,http://127.0.0.1}
    volumes:
      - static_volume:/app/staticfiles
      - ./Data:/app/Data:ro
    restart: unless-stopped
    
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./auth/.htpasswd:/etc/nginx/.htpasswd
      - static_volume:/app/staticfiles:ro
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped

volumes:
  static_volume: